### ISSUE TITLE
Review of tutorial

### ISSUE THREAD

**Issue by abelsiqueira** [jso-docs/solve-pdenlpmodels-with-jsosolvers#2]
Hi @tmigot, great tutorial, thanks for making it. I have a few suggestions and I will tag @dpo if he has any comments as well.

- [x] Remove the first title (it is added automatically).
- [x] Use math of Omega = (-1,1)^2 and similar. Unless you want it to be code, in which case I suggest using backticks.
- [x] Some sentences read like titles, like "Definition of the domain and discretization". I recommend changing it to a description and treating it like a paragraph, e.g., "First, we define the domain and discretization of the problem."
- [x] https://github.com/jso-docs/solve-pdenlpmodels-with-jsosolvers/blob/main/index.jl#L75 - You are already in a comment, so you define `#` and `##`, which breaks the formatting.
- [x] I think it would probably be better to limit the solving to DCI, to make the tutorial more focused.
- [x] I would actually change the title to "Solve a PDE-constrained optimization problem".

To finalize, you also have to
- [x] Make a pull request to jso-docs file `utils.jl` to fix the badges for NLPModelsModifiers and PDENLPModels. There is a const variable for the jso packages.
- [x] Make a pull request to jso-docs file `_data/tutorial.json` or something like that to add the tutorial.

**Comment by tmigot** [comment]
Thanks @abelsiqueira for the comments! I covered most of them already :) with direct commits.

Just a couple of comments.
I like the idea of having both Ipopt and DCI in this tutorial as it shows that DCI is doing great compared to Ipopt.

For the badges in `utils.jl`: Should I add all the JSO packages? Or you prefer to do it step by step?

**Comment by abelsiqueira** [comment]
Thanks! No problem, you can leave Ipopt. For the badges, you can add all released packages, that would be great. Feel free to close this whenever you want.
